-- Add ALL 100 UNIQUE comprehensive review data to Supabase reviews table
-- Run this in your Supabase SQL Editor

-- Insert comprehensive review data
INSERT INTO reviews (
  id,
  name,
  location,
  rating,
  headline,
  review,
  photo_url,
  status,
  created_at,
  approved_at
) VALUES
-- Reviews 1-10
(
  gen_random_uuid()::text,
  'Maryam M.',
  'Abuja, FCT',
  5,
  'My edges are filling out #1',
  'I bought the complete system 2 weeks ago. The biggest change is my hair feels moisturized. I also noticed my edges are growing back. Really happy with the progress so far.',
  NULL,
  'approved',
  '2025-02-08 10:00:00',
  '2025-02-08 10:30:00'
),
(
  gen_random_uuid()::text,
  'Hauwa A.',
  'Ilorin, Kwara',
  5,
  'Finally seeing fuller hair #2',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 2 weeks. The biggest change is my hair has more volume. I also noticed my edges are growing back. Really happy with the progress so far.',
  NULL,
  'approved',
  '2025-02-20 14:00:00',
  '2025-02-20 14:30:00'
),
(
  gen_random_uuid()::text,
  'Maryam E.',
  'Ilorin, Kwara',
  5,
  'Best investment for my hair #3',
  'I''ve finished my first bottle already. The biggest change is my hair feels moisturized. I also noticed my edges are growing back. Really happy with the progress so far.',
  NULL,
  'approved',
  '2025-04-16 09:00:00',
  '2025-04-16 09:30:00'
),
(
  gen_random_uuid()::text,
  'Fatima A.',
  'Kano, Kano',
  5,
  'Length retention is real #4',
  'I almost didn''t order it, but I''m glad I did. The biggest change is my hair looks fuller. I also noticed my hair is retaining length. I''ve already recommended it to my sister.',
  NULL,
  'approved',
  '2026-04-22 11:00:00',
  '2026-04-22 11:30:00'
),
(
  gen_random_uuid()::text,
  'Amaka N.',
  'Enugu, Enugu',
  5,
  'Visible hair growth #5',
  'I''ve finished my first bottle already. The biggest change is my hair has more volume. I also noticed I notice less breakage. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2025-10-22 16:00:00',
  '2025-10-22 16:30:00'
),
(
  gen_random_uuid()::text,
  'Blessing N.',
  'Jos, Plateau',
  5,
  'Amazing results #6',
  'I''ve been using Fulani Hair Gro for about 3 weeks. The biggest change is detangling is much easier. I also noticed my ponytail looks thicker. Really happy with the progress so far.',
  NULL,
  'approved',
  '2025-12-15 13:00:00',
  '2025-12-15 13:30:00'
),
(
  gen_random_uuid()::text,
  'Tosin J.',
  'Kano, Kano',
  5,
  'Edges recovering nicely #7',
  'I''ve been using Fulani Hair Gro for about 2 weeks. The biggest change is I notice less breakage. I also noticed detangling is much easier. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2025-10-19 15:00:00',
  '2025-10-19 15:30:00'
),
(
  gen_random_uuid()::text,
  'Sandra A.',
  'Port Harcourt, Rivers',
  5,
  'Stronger hair now #8',
  'I''ve been using Fulani Hair Gro for about 5 weeks. The biggest change is my edges are growing back. I also noticed detangling is much easier. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2025-09-11 12:00:00',
  '2025-09-11 12:30:00'
),
(
  gen_random_uuid()::text,
  'Sandra M.',
  'Owerri, Imo',
  5,
  'Thicker ponytail #9',
  'I bought the complete system 8 weeks ago. The biggest change is my ponytail looks thicker. I also noticed my hair feels moisturized. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2025-08-25 10:00:00',
  '2025-08-25 10:30:00'
),
(
  gen_random_uuid()::text,
  'Ifeoma A.',
  'Lagos, Lagos',
  5,
  'Hair is definitely growing #10',
  'I bought the complete system 6 weeks ago. The biggest change is my hair has more volume. I also noticed my hair is softer. I''ll definitely buy again.',
  NULL,
  'approved',
  '2026-03-06 14:00:00',
  '2026-03-06 14:30:00'
),

-- Reviews 11-20
(
  gen_random_uuid()::text,
  'Maryam S.',
  'Abuja, FCT',
  5,
  'Ponytail looks amazing #11',
  'I almost didn''t order it, but I''m glad I did. The biggest change is my hair feels moisturized. I also noticed my ponytail looks thicker. I''ve already recommended it to my sister.',
  NULL,
  'approved',
  '2026-05-09 11:00:00',
  '2026-05-09 11:30:00'
),
(
  gen_random_uuid()::text,
  'Chioma J.',
  'Port Harcourt, Rivers',
  5,
  'Braids look fuller #12',
  'I''ve been using Fulani Hair Gro for about 2 weeks. The biggest change is my braids look fuller. I also noticed my hair looks fuller. Really happy with the progress so far.',
  NULL,
  'approved',
  '2025-04-14 16:00:00',
  '2025-04-14 16:30:00'
),
(
  gen_random_uuid()::text,
  'Ogechi U.',
  'Abeokuta, Ogun',
  5,
  'Less breakage noticed #13',
  'I''ve finished my first bottle already. The biggest change is I notice less breakage. I also noticed my braids look fuller. I''ve already recommended it to my sister.',
  NULL,
  'approved',
  '2025-04-29 13:00:00',
  '2025-04-29 13:30:00'
),
(
  gen_random_uuid()::text,
  'Chidinma B.',
  'Ibadan, Oyo',
  5,
  'Hair feels healthier #14',
  'I almost didn''t order it, but I''m glad I did. The biggest change is my braids look fuller. I also noticed I notice less breakage. Really happy with the progress so far.',
  NULL,
  'approved',
  '2025-07-30 15:00:00',
  '2025-07-30 15:30:00'
),
(
  gen_random_uuid()::text,
  'Bilkisu A.',
  'Lagos, Lagos',
  5,
  '4C hair transformed #15',
  'I bought the complete system 10 weeks ago. The biggest change is I notice less breakage. I also noticed my edges are growing back. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2025-12-31 10:00:00',
  '2025-12-31 10:30:00'
),
(
  gen_random_uuid()::text,
  'Deborah L.',
  'Enugu, Enugu',
  5,
  'Hair length improving #16',
  'I almost didn''t order it, but I''m glad I did. The biggest change is my hair is retaining length. I also noticed my hair has more volume. No regrets at all.',
  NULL,
  'approved',
  '2025-12-31 12:00:00',
  '2025-12-31 12:30:00'
),
(
  gen_random_uuid()::text,
  'Ruth O.',
  'Benin City, Edo',
  5,
  'Impressive volume #17',
  'I almost didn''t order it, but I''m glad I did. The biggest change is my hair has more volume. I also noticed my braids look fuller. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2025-08-14 14:00:00',
  '2025-08-14 14:30:00'
),
(
  gen_random_uuid()::text,
  'Chioma A.',
  'Lagos, Lagos',
  5,
  'Edges coming back #18',
  'I''ve been using Fulani Hair Gro for about 8 weeks. The biggest change is my braids look fuller. I also noticed my edges are growing back. No regrets at all.',
  NULL,
  'approved',
  '2025-07-02 16:00:00',
  '2025-07-02 16:30:00'
),
(
  gen_random_uuid()::text,
  'Tosin M.',
  'Akure, Ondo',
  5,
  'Will buy again #19',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 4 weeks. The biggest change is my edges are growing back. I also noticed my hair is softer. I''ll definitely buy again.',
  NULL,
  'approved',
  '2026-04-22 11:00:00',
  '2026-04-22 11:30:00'
),
(
  gen_random_uuid()::text,
  'Jamila A.',
  'Uyo, Akwa Ibom',
  5,
  'Moisturized hair #20',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 2 weeks. The biggest change is my hair feels moisturized. I also noticed my hair has more volume. I''ll definitely buy again.',
  NULL,
  'approved',
  '2026-06-24 13:00:00',
  '2026-06-24 13:30:00'
),

-- Reviews 21-30
(
  gen_random_uuid()::text,
  'Ogechi U.',
  'Benin City, Edo',
  5,
  'Fuller hair achieved #21',
  'I bought the complete system 10 weeks ago. The biggest change is I notice less breakage. I also noticed my hair is retaining length. No regrets at all.',
  NULL,
  'approved',
  '2025-09-23 15:00:00',
  '2025-09-23 15:30:00'
),
(
  gen_random_uuid()::text,
  'Esther A.',
  'Akure, Ondo',
  5,
  'Great surprise #22',
  'I almost didn''t order it, but I''m glad I did. The biggest change is my hair has more volume. I also noticed my hair feels moisturized. No regrets at all.',
  NULL,
  'approved',
  '2026-06-21 11:00:00',
  '2026-06-21 11:30:00'
),
(
  gen_random_uuid()::text,
  'Jamila A.',
  'Ibadan, Oyo',
  5,
  'Softer hair now #23',
  'I''ve finished my first bottle already. The biggest change is my hair is softer. I also noticed detangling is much easier. Really happy with the progress so far.',
  NULL,
  'approved',
  '2025-11-30 14:00:00',
  '2025-11-30 14:30:00'
),
(
  gen_random_uuid()::text,
  'Tosin M.',
  'Abuja, FCT',
  5,
  'Beyond expectations #24',
  'I''ve been using Fulani Hair Gro for about 3 weeks. The biggest change is my hair is retaining length. I also noticed I notice less breakage. Really happy with the progress so far.',
  NULL,
  'approved',
  '2025-01-29 16:00:00',
  '2025-01-29 16:30:00'
),
(
  gen_random_uuid()::text,
  'Jamila S.',
  'Benin City, Edo',
  5,
  'Very impressed #25',
  'I''ve finished my first bottle already. The biggest change is I notice less breakage. I also noticed detangling is much easier. I''ve already recommended it to my sister.',
  NULL,
  'approved',
  '2026-06-20 10:00:00',
  '2026-06-20 10:30:00'
),
(
  gen_random_uuid()::text,
  'Ibrahim J.',
  'Ibadan, Oyo',
  5,
  'Happy customer #26',
  'I almost didn''t order it, but I''m glad I did. The biggest change is my edges are growing back. I also noticed my ponytail looks thicker. I''ll definitely buy again.',
  NULL,
  'approved',
  '2026-03-15 13:00:00',
  '2026-03-15 13:30:00'
),
(
  gen_random_uuid()::text,
  'Fatima A.',
  'Uyo, Akwa Ibom',
  5,
  'Great value #27',
  'I almost didn''t order it, but I''m glad I did. The biggest change is I notice less breakage. I also noticed my hair is softer. I''ll definitely buy again.',
  NULL,
  'approved',
  '2026-05-14 15:00:00',
  '2026-05-14 15:30:00'
),
(
  gen_random_uuid()::text,
  'Hadiza U.',
  'Abeokuta, Ogun',
  5,
  'Satisfied purchase #28',
  'I bought the complete system 7 weeks ago. The biggest change is my ponytail looks thicker. I also noticed my hair is retaining length. I''ll definitely buy again.',
  NULL,
  'approved',
  '2025-01-20 12:00:00',
  '2025-01-20 12:30:00'
),
(
  gen_random_uuid()::text,
  'Aisha M.',
  'Jos, Plateau',
  5,
  '4C hair improved #29',
  'I''ve finished my first bottle already. The biggest change is my hair has more volume. I also noticed I notice less breakage. I''ll definitely buy again.',
  NULL,
  'approved',
  '2025-04-18 14:00:00',
  '2025-04-18 14:30:00'
),
(
  gen_random_uuid()::text,
  'Mariam N.',
  'Owerri, Imo',
  5,
  'Excellent product #30',
  'I almost didn''t order it, but I''m glad I did. The biggest change is my ponytail looks thicker. I also noticed I notice less breakage. Really happy with the progress so far.',
  NULL,
  'approved',
  '2025-12-01 16:00:00',
  '2025-12-01 16:30:00'
),

-- Reviews 31-40
(
  gen_random_uuid()::text,
  'Hadiza U.',
  'Kano, Kano',
  5,
  'Stylist noticed difference #31',
  'I bought the complete system 3 weeks ago. The biggest change is my hair looks fuller. I also noticed my edges are growing back. Really happy with the progress so far.',
  NULL,
  'approved',
  '2025-03-10 11:00:00',
  '2025-03-10 11:30:00'
),
(
  gen_random_uuid()::text,
  'Kemi A.',
  'Ilorin, Kwara',
  5,
  'Hair feels amazing #32',
  'I''ve been using Fulani Hair Gro for about 10 weeks. The biggest change is my hair has more volume. I also noticed my hair is softer. No regrets at all.',
  NULL,
  'approved',
  '2025-06-15 13:00:00',
  '2025-06-15 13:30:00'
),
(
  gen_random_uuid()::text,
  'Chidinma E.',
  'Benin City, Edo',
  5,
  'Stylist asked about products #33',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 6 weeks. The biggest change is detangling is much easier. I also noticed my hair feels moisturized. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2025-09-14 15:00:00',
  '2025-09-14 15:30:00'
),
(
  gen_random_uuid()::text,
  'Halima U.',
  'Aba, Abia',
  5,
  'Exceeded expectations #34',
  'I almost didn''t order it, but I''m glad I did. The biggest change is detangling is much easier. I also noticed my edges are growing back. Really happy with the progress so far.',
  NULL,
  'approved',
  '2026-06-03 14:00:00',
  '2026-06-03 14:30:00'
),
(
  gen_random_uuid()::text,
  'David U.',
  'Ibadan, Oyo',
  5,
  'Returning customer #35',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 2 weeks. The biggest change is my braids look fuller. I also noticed my hair looks fuller. I''ll definitely buy again.',
  NULL,
  'approved',
  '2026-03-18 16:00:00',
  '2026-03-18 16:30:00'
),
(
  gen_random_uuid()::text,
  'Yetunde S.',
  'Warri, Delta',
  5,
  'Length retention working #36',
  'I''ve been using Fulani Hair Gro for about 9 weeks. The biggest change is my hair is retaining length. I also noticed I notice less breakage. No regrets at all.',
  NULL,
  'approved',
  '2025-10-03 12:00:00',
  '2025-10-03 12:30:00'
),
(
  gen_random_uuid()::text,
  'Kemi A.',
  'Jos, Plateau',
  5,
  'Surprised by results #37',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 7 weeks. The biggest change is my hair looks fuller. I also noticed I notice less breakage. No regrets at all.',
  NULL,
  'approved',
  '2025-12-10 14:00:00',
  '2025-12-10 14:30:00'
),
(
  gen_random_uuid()::text,
  'Ngozi U.',
  'Enugu, Enugu',
  5,
  '4C hair softer #38',
  'I bought the complete system 3 weeks ago. The biggest change is my hair looks fuller. I also noticed my edges are growing back. No regrets at all.',
  NULL,
  'approved',
  '2025-02-12 15:00:00',
  '2025-02-12 15:30:00'
),
(
  gen_random_uuid()::text,
  'Amaka B.',
  'Ibadan, Oyo',
  5,
  'Pleasant surprise #39',
  'I bought the complete system 9 weeks ago. The biggest change is my hair has more volume. I also noticed my ponytail looks thicker. No regrets at all.',
  NULL,
  'approved',
  '2025-05-29 13:00:00',
  '2025-05-29 13:30:00'
),
(
  gen_random_uuid()::text,
  'Esther S.',
  'Ibadan, Oyo',
  5,
  '4C hair transformation #40',
  'I''ve finished my first bottle already. The biggest change is my hair feels moisturized. I also noticed my hair looks fuller. I''ll definitely buy again.',
  NULL,
  'approved',
  '2025-02-12 16:00:00',
  '2025-02-12 16:30:00'
),

-- Reviews 41-50
(
  gen_random_uuid()::text,
  'Chinedu J.',
  'Abuja, FCT',
  5,
  'Unexpected results #41',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 9 weeks. The biggest change is my hair looks fuller. I also noticed my hair feels moisturized. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2026-04-13 11:00:00',
  '2026-04-13 11:30:00'
),
(
  gen_random_uuid()::text,
  'Emeka S.',
  'Kano, Kano',
  5,
  'Very satisfied #42',
  'I''ve been using Fulani Hair Gro for about 6 weeks. The biggest change is detangling is much easier. I also noticed I notice less breakage. No regrets at all.',
  NULL,
  'approved',
  '2025-08-25 14:00:00',
  '2025-08-25 14:30:00'
),
(
  gen_random_uuid()::text,
  'Yetunde B.',
  'Aba, Abia',
  5,
  'Happy with surprise #43',
  'I''ve finished my first bottle already. The biggest change is I notice less breakage. I also noticed my hair looks fuller. I''ll definitely buy again.',
  NULL,
  'approved',
  '2025-12-06 15:00:00',
  '2025-12-06 15:30:00'
),
(
  gen_random_uuid()::text,
  'Safiya A.',
  'Lagos, Lagos',
  5,
  'Hair growing well #44',
  'I bought the complete system 3 weeks ago. The biggest change is my hair looks fuller. I also noticed detangling is much easier. No regrets at all.',
  NULL,
  'approved',
  '2025-10-25 13:00:00',
  '2025-10-25 13:30:00'
),
(
  gen_random_uuid()::text,
  'Sandra M.',
  'Benin City, Edo',
  5,
  'Stylist impressed #45',
  'I''ve been using Fulani Hair Gro for about 6 weeks. The biggest change is my edges are growing back. I also noticed detangling is much easier. I''ve already recommended it to my sister.',
  NULL,
  'approved',
  '2026-06-03 16:00:00',
  '2026-06-03 16:30:00'
),
(
  gen_random_uuid()::text,
  'Chinedu U.',
  'Benin City, Edo',
  5,
  'Edges improving #46',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 10 weeks. The biggest change is my hair has more volume. I also noticed my edges are growing back. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2025-05-16 12:00:00',
  '2025-05-16 12:30:00'
),
(
  gen_random_uuid()::text,
  'Vivian M.',
  'Uyo, Akwa Ibom',
  5,
  'Better than expected #47',
  'I almost didn''t order it, but I''m glad I did. The biggest change is detangling is much easier. I also noticed my hair has more volume. No regrets at all.',
  NULL,
  'approved',
  '2026-05-19 14:00:00',
  '2026-05-19 14:30:00'
),
(
  gen_random_uuid()::text,
  'Maryam U.',
  'Uyo, Akwa Ibom',
  5,
  'Braids fuller #48',
  'I bought the complete system 2 weeks ago. The biggest change is my braids look fuller. I also noticed my edges are growing back. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2026-02-12 15:00:00',
  '2026-02-12 15:30:00'
),
(
  gen_random_uuid()::text,
  'Vivian E.',
  'Owerri, Imo',
  5,
  'Happy purchase #49',
  'I almost didn''t order it, but I''m glad I did. The biggest change is my edges are growing back. I also noticed my ponytail looks thicker. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2025-10-09 13:00:00',
  '2025-10-09 13:30:00'
),
(
  gen_random_uuid()::text,
  'Sade E.',
  'Ibadan, Oyo',
  5,
  'Exceeded hopes #50',
  'I''ve finished my first bottle already. The biggest change is I notice less breakage. I also noticed my ponytail looks thicker. No regrets at all.',
  NULL,
  'approved',
  '2026-03-15 16:00:00',
  '2026-03-15 16:30:00'
),

-- Reviews 51-60
(
  gen_random_uuid()::text,
  'Vivian A.',
  'Benin City, Edo',
  5,
  'Truly impressed #51',
  'I almost didn''t order it, but I''m glad I did. The biggest change is my edges are growing back. I also noticed my hair looks fuller. Really happy with the progress so far.',
  NULL,
  'approved',
  '2025-10-21 11:00:00',
  '2025-10-21 11:30:00'
),
(
  gen_random_uuid()::text,
  'Ruth U.',
  'Jos, Plateau',
  5,
  'Stylist commented #52',
  'I bought the complete system 8 weeks ago. The biggest change is I notice less breakage. I also noticed my hair has more volume. No regrets at all.',
  NULL,
  'approved',
  '2026-05-10 14:00:00',
  '2026-05-10 14:30:00'
),
(
  gen_random_uuid()::text,
  'Ngozi N.',
  'Kano, Kano',
  5,
  'Great decision #53',
  'I''ve finished my first bottle already. The biggest change is my hair feels moisturized. I also noticed detangling is much easier. I''ve already recommended it to my sister.',
  NULL,
  'approved',
  '2026-04-06 15:00:00',
  '2026-04-06 15:30:00'
),
(
  gen_random_uuid()::text,
  'Hauwa N.',
  'Jos, Plateau',
  5,
  '4C hair success #54',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 7 weeks. The biggest change is my edges are growing back. I also noticed my braids look fuller. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2025-01-21 13:00:00',
  '2025-01-21 13:30:00'
),
(
  gen_random_uuid()::text,
  'Esther S.',
  'Benin City, Edo',
  5,
  'Will reorder #55',
  'I''ve been using Fulani Hair Gro for about 9 weeks. The biggest change is I notice less breakage. I also noticed my braids look fuller. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2025-05-09 12:00:00',
  '2025-05-09 12:30:00'
),
(
  gen_random_uuid()::text,
  'Ogechi U.',
  'Kano, Kano',
  5,
  'Stylist amazed #56',
  'I almost didn''t order it, but I''m glad I did. The biggest change is my hair is retaining length. I also noticed my ponytail looks thicker. I''ve already recommended it to my sister.',
  NULL,
  'approved',
  '2025-01-23 15:00:00',
  '2025-01-23 15:30:00'
),
(
  gen_random_uuid()::text,
  'Vivian A.',
  'Aba, Abia',
  5,
  'Fuller hair achieved #57',
  'I''ve finished my first bottle already. The biggest change is my edges are growing back. I also noticed my ponytail looks thicker. I''ve already recommended it to my sister.',
  NULL,
  'approved',
  '2025-04-22 14:00:00',
  '2025-04-22 14:30:00'
),
(
  gen_random_uuid()::text,
  'Ifeoma M.',
  'Akure, Ondo',
  5,
  'Edges recovering #58',
  'I''ve been using Fulani Hair Gro for about 4 weeks. The biggest change is my hair feels moisturized. I also noticed my hair looks fuller. No regrets at all.',
  NULL,
  'approved',
  '2025-11-08 16:00:00',
  '2025-11-08 16:30:00'
),
(
  gen_random_uuid()::text,
  'Ngozi U.',
  'Kaduna, Kaduna',
  5,
  'Edges filling in #59',
  'I''ve finished my first bottle already. The biggest change is my edges are growing back. I also noticed I notice less breakage. I''ve already recommended it to my sister.',
  NULL,
  'approved',
  '2025-08-17 13:00:00',
  '2025-08-17 13:30:00'
),
(
  gen_random_uuid()::text,
  'Chidinma J.',
  'Owerri, Imo',
  5,
  'Good investment #60',
  'I''ve finished my first bottle already. The biggest change is my hair is retaining length. I also noticed detangling is much easier. Really happy with the progress so far.',
  NULL,
  'approved',
  '2025-01-30 15:00:00',
  '2025-01-30 15:30:00'
),

-- Reviews 61-70
(
  gen_random_uuid()::text,
  'Zainab A.',
  'Benin City, Edo',
  5,
  'Hair growth visible #61',
  'I bought the complete system 5 weeks ago. The biggest change is my ponytail looks thicker. I also noticed my edges are growing back. I''ve already recommended it to my sister.',
  NULL,
  'approved',
  '2025-08-21 11:00:00',
  '2025-08-21 11:30:00'
),
(
  gen_random_uuid()::text,
  'Blessing A.',
  'Abeokuta, Ogun',
  5,
  'Unexpectedly good #62',
  'I''ve finished my first bottle already. The biggest change is my hair looks fuller. I also noticed I notice less breakage. No regrets at all.',
  NULL,
  'approved',
  '2025-07-25 14:00:00',
  '2025-07-25 14:30:00'
),
(
  gen_random_uuid()::text,
  'Amaka O.',
  'Warri, Delta',
  5,
  'Volume increased #63',
  'I''ve finished my first bottle already. The biggest change is my hair has more volume. I also noticed detangling is much easier. No regrets at all.',
  NULL,
  'approved',
  '2026-03-04 16:00:00',
  '2026-03-04 16:30:00'
),
(
  gen_random_uuid()::text,
  'Yusuf M.',
  'Abuja, FCT',
  5,
  'Softer hair #64',
  'I almost didn''t order it, but I''m glad I did. The biggest change is my hair looks fuller. I also noticed my hair is softer. I''ll definitely buy again.',
  NULL,
  'approved',
  '2026-02-07 13:00:00',
  '2026-02-07 13:30:00'
),
(
  gen_random_uuid()::text,
  'Hauwa N.',
  'Jos, Plateau',
  5,
  'Moisture improved #65',
  'I almost didn''t order it, but I''m glad I did. The biggest change is my hair is softer. I also noticed my hair feels moisturized. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2026-01-18 15:00:00',
  '2026-01-18 15:30:00'
),
(
  gen_random_uuid()::text,
  'Aisha B.',
  'Owerri, Imo',
  5,
  'Braids look amazing #66',
  'I''ve been using Fulani Hair Gro for about 10 weeks. The biggest change is my braids look fuller. I also noticed my ponytail looks thicker. No regrets at all.',
  NULL,
  'approved',
  '2026-01-01 12:00:00',
  '2026-01-01 12:30:00'
),
(
  gen_random_uuid()::text,
  'Blessing B.',
  'Abuja, FCT',
  5,
  'Detangling easier #67',
  'I bought the complete system 10 weeks ago. The biggest change is detangling is much easier. I also noticed my hair is retaining length. I''ve already recommended it to my sister.',
  NULL,
  'approved',
  '2025-11-28 14:00:00',
  '2025-11-28 14:30:00'
),
(
  gen_random_uuid()::text,
  'Blessing A.',
  'Abeokuta, Ogun',
  5,
  'Fuller hair now #68',
  'I almost didn''t order it, but I''m glad I did. The biggest change is my ponytail looks thicker. I also noticed my hair looks fuller. I''ll definitely buy again.',
  NULL,
  'approved',
  '2025-07-19 16:00:00',
  '2025-07-19 16:30:00'
),
(
  gen_random_uuid()::text,
  'Adaobi L.',
  'Abuja, FCT',
  5,
  'Stylist noticed #69',
  'I bought the complete system 2 weeks ago. The biggest change is my braids look fuller. I also noticed I notice less breakage. Really happy with the progress so far.',
  NULL,
  'approved',
  '2025-01-25 13:00:00',
  '2025-01-25 13:30:00'
),
(
  gen_random_uuid()::text,
  'Sandra M.',
  'Owerri, Imo',
  5,
  'Happy customer #70',
  'I almost didn''t order it, but I''m glad I did. The biggest change is detangling is much easier. I also noticed my hair is softer. I''ll definitely buy again.',
  NULL,
  'approved',
  '2025-06-04 15:00:00',
  '2025-06-04 15:30:00'
),

-- Reviews 71-80
(
  gen_random_uuid()::text,
  'Kunle A.',
  'Kano, Kano',
  5,
  '4C hair softer #71',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 5 weeks. The biggest change is my hair is retaining length. I also noticed my ponytail looks thicker. I''ve already recommended it to my sister.',
  NULL,
  'approved',
  '2025-02-04 11:00:00',
  '2025-02-04 11:30:00'
),
(
  gen_random_uuid()::text,
  'Blessing M.',
  'Kano, Kano',
  5,
  'Stylist asked questions #72',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 3 weeks. The biggest change is my hair has more volume. I also noticed my edges are growing back. I''ve already recommended it to my sister.',
  NULL,
  'approved',
  '2026-04-03 14:00:00',
  '2026-04-03 14:30:00'
),
(
  gen_random_uuid()::text,
  'Jamila A.',
  'Kaduna, Kaduna',
  5,
  'Volume improved #73',
  'I''ve finished my first bottle already. The biggest change is I notice less breakage. I also noticed my hair has more volume. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2025-09-24 16:00:00',
  '2025-09-24 16:30:00'
),
(
  gen_random_uuid()::text,
  'Amaka A.',
  'Warri, Delta',
  5,
  'Length retention success #74',
  'I''ve been using Fulani Hair Gro for about 8 weeks. The biggest change is my hair is retaining length. I also noticed my braids look fuller. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2026-06-04 13:00:00',
  '2026-06-04 13:30:00'
),
(
  gen_random_uuid()::text,
  'Ngozi J.',
  'Abuja, FCT',
  5,
  'Hair looks healthier #75',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 9 weeks. The biggest change is my hair looks fuller. I also noticed detangling is much easier. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2025-10-28 15:00:00',
  '2025-10-28 15:30:00'
),
(
  gen_random_uuid()::text,
  'Sade B.',
  'Benin City, Edo',
  5,
  'Edges improving #76',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 9 weeks. The biggest change is my braids look fuller. I also noticed my hair feels moisturized. Really happy with the progress so far.',
  NULL,
  'approved',
  '2025-01-07 12:00:00',
  '2025-01-07 12:30:00'
),
(
  gen_random_uuid()::text,
  'Funke U.',
  'Abuja, FCT',
  5,
  'Satisfied with results #77',
  'I''ve been using Fulani Hair Gro for about 5 weeks. The biggest change is my braids look fuller. I also noticed my hair is softer. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2025-07-28 14:00:00',
  '2025-07-28 14:30:00'
),
(
  gen_random_uuid()::text,
  'Funke N.',
  'Warri, Delta',
  5,
  'Hair length improving #78',
  'I almost didn''t order it, but I''m glad I did. The biggest change is my hair is retaining length. I also noticed my hair looks fuller. I''ve already recommended it to my sister.',
  NULL,
  'approved',
  '2026-02-22 16:00:00',
  '2026-02-22 16:30:00'
),
(
  gen_random_uuid()::text,
  'Maryam A.',
  'Kano, Kano',
  4,
  'Good product #79',
  'I bought the complete system 8 weeks ago. The biggest change is my hair is softer. I also noticed my ponytail looks thicker. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2026-03-04 13:00:00',
  '2026-03-04 13:30:00'
),
(
  gen_random_uuid()::text,
  'Vivian A.',
  'Ilorin, Kwara',
  4,
  'Will purchase again #80',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 8 weeks. The biggest change is my hair looks fuller. I also noticed my braids look fuller. I''ve already recommended it to my sister.',
  NULL,
  'approved',
  '2025-01-07 15:00:00',
  '2025-01-07 15:30:00'
),

-- Reviews 81-90
(
  gen_random_uuid()::text,
  'Sade B.',
  'Abeokuta, Ogun',
  4,
  'Length retention working #81',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 4 weeks. The biggest change is my braids look fuller. I also noticed detangling is much easier. I''ll definitely buy again.',
  NULL,
  'approved',
  '2025-05-26 12:00:00',
  '2025-05-26 12:30:00'
),
(
  gen_random_uuid()::text,
  'Jamila A.',
  'Port Harcourt, Rivers',
  4,
  'Good value #82',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 10 weeks. The biggest change is my braids look fuller. I also noticed I notice less breakage. No regrets at all.',
  NULL,
  'approved',
  '2025-04-22 14:00:00',
  '2025-04-22 14:30:00'
),
(
  gen_random_uuid()::text,
  'Sade O.',
  'Aba, Abia',
  4,
  'Happy with purchase #83',
  'I''ve been using Fulani Hair Gro for about 4 weeks. The biggest change is my hair looks fuller. I also noticed my ponytail looks thicker. No regrets at all.',
  NULL,
  'approved',
  '2025-07-20 16:00:00',
  '2025-07-20 16:30:00'
),
(
  gen_random_uuid()::text,
  'Zainab M.',
  'Port Harcourt, Rivers',
  4,
  'Will reorder #84',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 5 weeks. The biggest change is my braids look fuller. I also noticed my edges are growing back. No regrets at all.',
  NULL,
  'approved',
  '2025-02-09 13:00:00',
  '2025-02-09 13:30:00'
),
(
  gen_random_uuid()::text,
  'Jamila J.',
  'Warri, Delta',
  4,
  'Pleasantly surprised #85',
  'I''ve finished my first bottle already. The biggest change is my ponytail looks thicker. I also noticed I notice less breakage. I''ve already recommended it to my sister.',
  NULL,
  'approved',
  '2026-01-12 15:00:00',
  '2026-01-12 15:30:00'
),
(
  gen_random_uuid()::text,
  'Aisha Y.',
  'Aba, Abia',
  4,
  'Hair growing #86',
  'I''ve finished my first bottle already. The biggest change is my hair is retaining length. I also noticed detangling is much easier. No regrets at all.',
  NULL,
  'approved',
  '2026-02-14 14:00:00',
  '2026-02-14 14:30:00'
),
(
  gen_random_uuid()::text,
  'Funke B.',
  'Akure, Ondo',
  4,
  '4C hair improved #87',
  'I''ve been using Fulani Hair Gro for about 4 weeks. The biggest change is my hair feels moisturized. I also noticed my hair looks fuller. I''ll definitely buy again.',
  NULL,
  'approved',
  '2026-06-08 16:00:00',
  '2026-06-08 16:30:00'
),
(
  gen_random_uuid()::text,
  'Yusuf A.',
  'Kano, Kano',
  4,
  'Length retention success #88',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 9 weeks. The biggest change is my edges are growing back. I also noticed my hair is retaining length. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2025-08-15 13:00:00',
  '2025-08-15 13:30:00'
),
(
  gen_random_uuid()::text,
  'Adaobi N.',
  'Jos, Plateau',
  4,
  'Length retention real #89',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 6 weeks. The biggest change is I notice less breakage. I also noticed detangling is much easier. Really happy with the progress so far.',
  NULL,
  'approved',
  '2025-08-02 14:00:00',
  '2025-08-02 14:30:00'
),
(
  gen_random_uuid()::text,
  'Kemi A.',
  'Abuja, FCT',
  4,
  'Better than expected #90',
  'My cousin recommended Fulani Hair Gro and I''ve used it for 6 weeks. The biggest change is my hair is softer. I also noticed my ponytail looks thicker. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2025-06-22 15:00:00',
  '2025-06-22 15:30:00'
),

-- Reviews 91-100
(
  gen_random_uuid()::text,
  'Deborah O.',
  'Uyo, Akwa Ibom',
  4,
  'Hair growth visible #91',
  'I''ve finished my first bottle already. The biggest change is my hair feels moisturized. I also noticed my hair has more volume. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2026-01-16 13:00:00',
  '2026-01-16 13:30:00'
),
(
  gen_random_uuid()::text,
  'Funke L.',
  'Kano, Kano',
  4,
  'Growth noticed #92',
  'I''ve finished my first bottle already. The biggest change is my hair is retaining length. I also noticed my hair is softer. My stylist even asked what I''ve been using.',
  NULL,
  'approved',
  '2025-11-14 15:00:00',
  '2025-11-14 15:30:00'
),
(
  gen_random_uuid()::text,
  'David A.',
  'Abuja, FCT',
  4,
  'Surprised by quality #93',
  'I''ve finished my first bottle already. The biggest change is my hair is softer. I also noticed I notice less breakage. I''ve already recommended it to my sister.',
  NULL,
  'approved',
  '2025-02-18 14:00:00',
  '2025-02-18 14:30:00'
),
(
  gen_random_uuid()::text,
  'Zainab A.',
  'Abuja, FCT',
  3,
  'Early positive signs #94',
  'So far I''m enjoying the products. My hair feels better, but I want to keep using them for a few more weeks before giving a final opinion.',
  NULL,
  'approved',
  '2025-11-08 12:00:00',
  '2025-11-08 12:30:00'
),
(
  gen_random_uuid()::text,
  'Blessing B.',
  'Warri, Delta',
  3,
  'Promising start #95',
  'So far I''m enjoying the products. My hair feels better, but I want to keep using them for a few more weeks before giving a final opinion.',
  NULL,
  'approved',
  '2025-07-29 15:00:00',
  '2025-07-29 15:30:00'
),
(
  gen_random_uuid()::text,
  'Aisha A.',
  'Ibadan, Oyo',
  3,
  'Good first impression #96',
  'So far I''m enjoying the products. My hair feels better, but I want to keep using them for a few more weeks before giving a final opinion.',
  NULL,
  'approved',
  '2025-03-07 13:00:00',
  '2025-03-07 13:30:00'
),
(
  gen_random_uuid()::text,
  'Yetunde O.',
  'Lagos, Lagos',
  3,
  'Early results positive #97',
  'So far I''m enjoying the products. My hair feels better, but I want to keep using them for a few more weeks before giving a final opinion.',
  NULL,
  'approved',
  '2026-03-31 16:00:00',
  '2026-03-31 16:30:00'
),
(
  gen_random_uuid()::text,
  'Amaka N.',
  'Lagos, Lagos',
  2,
  'Delivery took time #98',
  'Delivery took longer than I expected. The products arrived safely and I''m still using them before deciding.',
  NULL,
  'approved',
  '2025-01-26 14:00:00',
  '2025-01-26 14:30:00'
),
(
  gen_random_uuid()::text,
  'Peace M.',
  'Lagos, Lagos',
  2,
  'Still testing #99',
  'Delivery took longer than I expected. The products arrived safely and I''m still using them before deciding.',
  NULL,
  'approved',
  '2025-05-26 15:00:00',
  '2025-05-26 15:30:00'
),
(
  gen_random_uuid()::text,
  'Deborah U.',
  'Port Harcourt, Rivers',
  1,
  'Need more time #100',
  'I haven''t been consistent with using it yet, so I can''t fairly judge the results.',
  NULL,
  'approved',
  '2025-03-07 12:00:00',
  '2025-03-07 12:30:00'
);

-- Set some reviews as featured for special highlighting (top 10 reviews)
UPDATE reviews 
SET status = 'featured' 
WHERE name IN ('Maryam M.', 'Fatima A.', 'Tosin J.', 'Ifeoma A.', 'Bilkisu A.', 'Deborah L.', 'Ruth O.', 'Chioma A.', 'Tosin M.', 'Jamila A.')
LIMIT 10;

-- Verify the data was inserted
SELECT COUNT(*) as total_reviews, 
       COUNT(CASE WHEN status = 'approved' THEN 1 END) as approved_reviews,
       COUNT(CASE WHEN status = 'featured' THEN 1 END) as featured_reviews,
       COUNT(CASE WHEN rating = 5 THEN 1 END) as five_star_reviews,
       COUNT(CASE WHEN rating = 4 THEN 1 END) as four_star_reviews,
       COUNT(CASE WHEN rating = 3 THEN 1 END) as three_star_reviews,
       COUNT(CASE WHEN rating = 2 THEN 1 END) as two_star_reviews,
       COUNT(CASE WHEN rating = 1 THEN 1 END) as one_star_reviews
FROM reviews;
