name: 🚀 Deploy bot on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🎉 Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: public_html/
          timeout: 190000
